<?php

namespace AppBundle\Repository;

/**
 * CartDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
