<?php

namespace AppBundle\Repository;

/**
 * CommandDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
