<?php

namespace AppBundle\Repository;

/**
 * DeliveryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
