parameters:
    fos_rest.view_response_listener.class: AppBundle\Listener\ViewResponseListener

services:
    app.listener.exception_listener:
        class: AppBundle\Listener\ExceptionListener
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }