services:
    app.param_converter.collection_param_converter:
        class: AppBundle\ParamConverter\CollectionParamConverter
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: request.param_converter, converter: collection_param_converter }
